// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6GO_TRID4t6KcSMguYWxMC6c93oRF_oc',
    appId: '1:1068407788715:web:5fe090fae2e5910a6013ee',
    messagingSenderId: '1068407788715',
    projectId: 'travelsapp-41249',
    authDomain: 'travelsapp-41249.firebaseapp.com',
    storageBucket: 'travelsapp-41249.firebasestorage.app',
    measurementId: 'G-HBH1R5N250',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17C7bDq6fglhdj68Wxt6AdYfka9NqbRk',
    appId: '1:1068407788715:android:add1e16b443155c96013ee',
    messagingSenderId: '1068407788715',
    projectId: 'travelsapp-41249',
    storageBucket: 'travelsapp-41249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDYjx3I-sJOiK6nk0hdOkEBAr0Wc-x2So',
    appId: '1:1068407788715:ios:2eacc8fedc8e56b16013ee',
    messagingSenderId: '1068407788715',
    projectId: 'travelsapp-41249',
    storageBucket: 'travelsapp-41249.firebasestorage.app',
    iosClientId: '1068407788715-9dhicmj7v16u34njm9jsv0q5reppaev4.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelapp2',
  );
}
